CREATE FUNCTION `testCreateQuery` (
	CNT INTEGER -- 파라미터선언 
)
RETURNS INTEGER
BEGIN
	SET i = 0;
	WHILE (i < CNT) DO
		SET RAND1 = (SUBSTRING(MD5(RAND()) FROM 1 FOR 8));
        SET RAND2 = (SUBSTRING(MD5(RAND()) FROM 1 FOR 8));
        SET RAND3 = (SELECT FLOOR(RAND() * 10000));
        
		INSERT INTO dangoon.board(M_ID, B_TYPE, B_WRITER, B_TITLE, B_CONTENT, B_CATEGORY, B_PRICE) VALUES(2, 'S', 'test1', RAND1, RAND2, 'ETC', RAND3);

		END WHILE;

RETURN 1;
END


